### PR TITLE
reduced, reused, and recyled code

### PR DESCRIPTION
**Pull request by jzmejia**
making pull request and resolving one conflict in gear-sharing.md article.

### CODE REVIEW

**Comment by jzmejia** [comment]
@liberaltech Netlify deploy preview failed. 

Netlify deploy log:

```
3:46:47 PM: [1/4] Resolving packages...
3:46:47 PM: [2/4] Fetching packages...
3:46:53 PM: warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
3:46:53 PM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
3:47:06 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
3:47:06 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
3:47:06 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
3:47:06 PM: info fsevents@2.3.3: The platform "linux" is incompatible with this module.
3:47:06 PM: info "fsevents@2.3.3" is an optional dependency and failed compatibility check. Excluding it from installation.
3:47:06 PM: error puppeteer@23.2.2: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.21.3"
3:47:06 PM: error Found incompatible module.
3:47:06 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
3:47:06 PM: Error during Yarn install
3:47:06 PM: Failing build: Failed to install dependencies
```


Diagnosis: The build failure is caused by an incompatible module issue with puppeteer. The error states that the engine "node" is incompatible with the puppeteer module, expecting version ">=18" but getting "14.21.3".

Solution: To resolve this error:
Update the Node.js version to be greater than or equal to 18 to meet the requirements of the puppeteer module.
Ensure that the Node.js version used in the project meets the minimum version required by any dependencies.

@liberaltech can you fix this on the `next-gen` branch? for  #69

**Review by liberaltech — APPROVED** [review]

**Comment by jzmejia** [comment]
@liberaltech I am checking the netlify build now to see if the site will deploy

**Comment by jzmejia** [comment]
@liberaltech the fix to `yarn` worked, but the node version is still giving errors

Screenshot 2024-10-01 at 11 14 39 AM

Deploy log failure:

Screenshot 2024-10-01 at 11 15 28 AM


Initialization - complete!
Build - Failed

Build log:
```bash
11:12:39 AM: build-image version: ecdc8b770f4a0193fd3f258c1bc6029e681813a4 (focal)
11:12:39 AM: buildbot version: f3084eaa8f828974f2a588ca06f184d562180d50
11:12:39 AM: Building without cache
11:12:39 AM: Starting to prepare the repo for build
11:12:39 AM: No cached dependencies found. Cloning fresh repo
11:12:39 AM: git clone --filter=blob:none https://github.com/jzmejia/CryoCommunity
11:12:40 AM: Preparing Git Reference pull/69/head
11:12:45 AM: Custom functions path detected. Proceeding with the specified path: 'netlify/functions'
11:12:46 AM: Starting to install dependencies
11:12:46 AM: Python version set to 3.8
11:12:46 AM: Attempting Ruby version 2.7.2, read from environment
11:12:47 AM: Using Ruby version 2.7.2
11:12:48 AM: Started restoring cached go cache
11:12:48 AM: Finished restoring cached go cache
11:12:48 AM: Installing Go version 1.16.5 (requested 1.16.5)
11:12:53 AM: go version go1.16.5 linux/amd64
11:12:54 AM: Using PHP version 8.0
11:12:56 AM: Attempting Node.js version 'node' from .nvmrc
11:12:58 AM: Downloading and installing node v22.9.0...
11:12:58 AM: Downloading https://nodejs.org/dist/v22.9.0/node-v22.9.0-linux-x64.tar.xz...
11:12:58 AM: Computing checksum with sha256sum
11:12:58 AM: Checksums matched!
11:13:01 AM: Now using node v22.9.0 (npm v10.8.3)
11:13:01 AM: Enabling Node.js Corepack
11:13:01 AM: Started restoring cached build plugins
11:13:01 AM: Finished restoring cached build plugins
11:13:01 AM: Started restoring cached corepack dependencies
11:13:01 AM: Finished restoring cached corepack dependencies
11:13:01 AM: Started restoring cached yarn cache
11:13:01 AM: Finished restoring cached yarn cache
11:13:01 AM: ! Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.22.tgz
11:13:02 AM: Installing Yarn version 1.22.10
11:13:02 AM: Preparing yarn@1.22.10 for immediate activation...
11:13:03 AM: No yarn workspaces detected
11:13:03 AM: Started restoring cached node modules
11:13:03 AM: Finished restoring cached node modules
11:13:03 AM: Installing npm packages using Yarn version 1.22.22
11:13:03 AM: yarn install v1.22.22
11:13:03 AM: [1/4] Resolving packages...
11:13:04 AM: [2/4] Fetching packages...
11:13:08 AM: warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
11:13:09 AM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
11:13:20 AM: [3/4] Linking dependencies...
11:13:20 AM: warning "gridsome-plugin-gtag > vue-gtag@1.16.1" has unmet peer dependency "vue@^2.0.0".
11:13:20 AM: warning " > vue-tweet-embed@2.4.0" has unmet peer dependency "vue@^2.2.0".
11:13:20 AM: warning " > vuetify@2.7.2" has unmet peer dependency "vue@^2.6.4".
11:13:20 AM: warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
11:13:20 AM: warning " > vue-svg-loader@0.16.0" has unmet peer dependency "vue-template-compiler@^2.0.0".
11:13:20 AM: warning "vue-svg-loader > svg-to-vue@0.7.0" has unmet peer dependency "vue-template-compiler@^2.0.0".
11:13:20 AM: warning " > vuetify-loader@1.9.2" has unmet peer dependency "vue@^2.7.2".
11:13:20 AM: warning " > vuetify-loader@1.9.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
11:13:20 AM: warning "vuetify-loader > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
11:13:27 AM: [4/4] Building fresh packages...
11:13:48 AM: Done in 45.11s.
11:13:48 AM: npm packages installed using Yarn
11:13:49 AM: Successfully installed dependencies
11:13:49 AM: Starting build script
11:13:51 AM: Detected 1 framework(s)
11:13:51 AM: "gridsome" at version "0.7.23"
11:13:51 AM: Section completed: initializing
11:13:53 AM: ​
11:13:53 AM: Netlify Build                                                 
11:13:53 AM: ────────────────────────────────────────────────────────────────
11:13:53 AM: ​
11:13:53 AM: ❯ Version
11:13:53 AM:   @netlify/build 29.54.6
11:13:53 AM: ​
11:13:53 AM: ❯ Flags
11:13:53 AM:   accountId: 6142b682d4fca279ed5548f3
11:13:53 AM:   baseRelDir: true
11:13:53 AM:   buildId: 66fc115490c7d95afa52f8a6
11:13:53 AM:   deployId: 66fc115490c7d95afa52f8a8
11:13:53 AM: ​
11:13:53 AM: ❯ Current directory
11:13:53 AM:   /opt/build/repo
11:13:53 AM: ​
11:13:53 AM: ❯ Config file
11:13:53 AM:   No config file was defined: using default values.
11:13:53 AM: ​
11:13:53 AM: ❯ Context
11:13:53 AM:   deploy-preview
11:13:53 AM: ​
11:13:53 AM: Build command from Netlify app                                
11:13:53 AM: ────────────────────────────────────────────────────────────────
11:13:53 AM: ​
11:13:53 AM: $ gridsome build
11:13:54 AM: Gridsome v0.7.23
11:13:54 AM: Initializing plugins...
11:13:54 AM: Error: gridsome.server.js: Cannot find module './functions/generateHtml'
11:13:55 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:13:54 AM: Require stack:
11:13:54 AM: - /opt/build/repo/gridsome.server.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/lib/app/Plugins.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/lib/app/App.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/lib/app/index.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/lib/build.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/index.js
11:13:54 AM: - /opt/build/repo/node_modules/@gridsome/cli/bin/gridsome.js
11:13:54 AM: - /opt/build/repo/node_modules/gridsome/bin/gridsome.js (17:22)
11:13:54 AM:   15 | const { readFile, access, ensureDirSync } = require("fs-extra");
11:13:54 AM:   16 | const createImage = require("node-html-to-image");
11:13:54 AM: > 17 | const generateHtml = require("./functions/generateHtml");
11:13:54 AM:      |                      ^
11:13:54 AM:   18 |
11:13:54 AM:   19 | const defaultOptions = {
11:13:54 AM:   20 |   typeName: "Article", // This should be the typeName noted above 📝
11:13:55 AM: ​
11:13:55 AM: "build.command" failed                                        
11:13:55 AM: ────────────────────────────────────────────────────────────────
11:13:55 AM: ​
11:13:55 AM:   Error message
11:13:55 AM:   Command failed with exit code 1: gridsome build (https://ntl.fyi/exit-code-1)
11:13:55 AM: ​
11:13:55 AM:   Error location
11:13:55 AM:   In Build command from Netlify app:
11:13:55 AM:   gridsome build
11:13:55 AM: ​
11:13:55 AM:   Resolved config
11:13:55 AM:   build:
11:13:55 AM:     command: gridsome build
11:13:55 AM:     commandOrigin: ui
11:13:55 AM:     environment:
11:13:55 AM:       - GOOGLE_ANALYTICS_ID
11:13:55 AM:       - GRIDSOME_ACCESS_TOKEN
11:13:55 AM:       - GRIDSOME_BEARER_TOKEN
11:13:55 AM:       - GRIDSOME_CONSUMER_KEY
11:13:55 AM:       - GRIDSOME_CONSUMER_SECRET
11:13:55 AM:       - GRIDSOME_NETLIFY_CENSUS_FORM_ID
11:13:55 AM:       - GRIDSOME_NETLIFY_PERSONAL_ACCESS_TOKEN
11:13:55 AM:       - GRIDSOME_SECRET_KEY
11:13:55 AM:       - GRIDSOME_TWITTER_ID
11:13:55 AM:       - GRIDSOME_TWITTER_USERNAME
11:13:55 AM:       - NODE_VERSION
11:13:55 AM:       - REVIEW_ID
11:13:55 AM:     publish: /opt/build/repo/dist
11:13:55 AM:     publishOrigin: ui
11:13:55 AM:   functionsDirectory: /opt/build/repo/netlify/functions
11:13:55 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:13:55 AM: Failing build: Failed to build site
11:13:55 AM: Finished processing build request in 1m16.438s
```

**Comment by jzmejia** [comment]
New error timeout:

```bash
2:26:30 PM: Process files (0 files) - 0s
2:43:32 PM: Failed during stage 'building site': Command did not finish within the time limit
2:43:32 PM: Processing images (125 images) - 0%Processing images (125 images) - 20%Processing images (125 images) - 40%Processing images (125 images) - 60%Processing images (125 images) - 80%
2:43:32 PM: Execution timed out after 17m59.930284868s
2:43:32 PM: Failing build: Failed to build site
2:43:33 PM: Finished processing build request in 18m56.359s
```

**Pull request merged**
